- hosts: all
  roles:
    - fetch-output

- hosts: localhost
  gather_facts: False
  roles:
    - generate-zuul-manifest
    - role: add-fileserver
      fileserver: "{{ site_logs }}"

- hosts: "{{ site_logs.hostname }}"
  gather_facts: False
  roles:
    - role: upload-logs
      zuul_logserver_root: "{{ site_logs.path }}"
      zuul_log_url: "http://3.125.206.5:8000"
